### PR TITLE
Feature: hide files and folders

### PR DESCRIPTION
**Pull request by RPJoshL**
This PR adds the function to hide files and folders by a regular expression or by the file extension. These files and folders won't be synced and shown in the UI. This applies for remote, locale and synced files.
Also, the default start folder when opening the app can now be set.

To configure the preferences for hiding files and folders, I've added a new View which is accessible over the main menu when logged in.

<p float="left">
  
   
</p>

Some notes to take in mind:

* Added column to `metadata` Table to save the "hidden" state → because of that, a database migration is necessary. So I've created a version table in the SQLite Database to add a migration functionality in the future
* The current (db) version will be set inside the `CMakeLists.txt`
* The exclusion happens currently only on the client. All files and folders will still be fetched from Nextcloud (except the start folder)

Since this was my first experience with *C++* (used only ANSI C for small things in the past), you may want to take a close look to the changes 😊

### CODE REVIEW

**Review by JuanJakobo — COMMENTED** [review]
Danke für den Pull Request!
I am thinking about creating an option menu and also put the "order items by" option into it. 
I got one question:
Why did you create the method getConfig in util.h and did not choose to use the existing accessConfig method? Would you propose to have one method set config and one get or what is the idea here? :)
Currently the accessConfig handles both cases.
The other things look great.
Thanks for automating the version number in the code and the other small things! 
I used this project to get better at C++ so it is always nice if somebody else at least understands what I am trying to code. haha

**Comment by JuanJakobo** [comment]
Just tested to logout and delete the config in the system/config folder. After it it seems as if the login is brocken due to the Startfolder missing or something like that. Did you test the case of a total new installation of the app?

**Comment by RPJoshL** [comment]
Thanks for your review and your first test. For me, it was a good starting point to get a little familiar with C++ and I was kindly interested how you would write an app for an E-Book reader 🧐️ And for that it was an excellent starting point.

During testing, I forget about deleting the config file (only logged out and deleted the db...). So sorry for the bad test coverage :) 
But I've looked at the problem, and it should now be fixed. It was a combination of not creating the pointer to the `EventHandler` and a missing UUID at login time. In this context I fixed another issue where an exception would be thrown during logout (after a failed login) because the file path to delete doesn't exist.

I was aware that you could read and write the configuration over the `AccessConfig` Method. But it was rather uncommon for me to change the fundamental behavior of a method through a flag. In addition, it lacked the function to set a default value so with the existing method I was unable to distinguish an empty Config or if the user wants to ignore something with the name "error". To make things more clear I've removed  now the `AccessConfig` Method and split the reading and writing into their own Methods. I think this should be clear now.

For me, it makes absolute sense to source these kinds of "customizations" into an extra Settings view to not blow up the menu in the future.

**Review by JuanJakobo — APPROVED** [review]
The testing is unfortunately not that easy as it is as far as I know not possible to setup a "real" testing. So no worries, Thank you!
Okay, thanks for making the AccessConfig Method more clear.

**Pull request merged**
